services:
  postgres:
    image: postgres:17
    restart: "no"
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: loginService
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  login-service:
    image: login-service:latest
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: root
      DB_PASSWORD: root
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - postgres
volumes:
  postgres_data: